title: John Doherty
email: john.doherty13@gmail.com
description: >-
  Welcome! This is a blog I will use to share projects, ideas, and interesting
  things I have learned.
baseurl: ""
url: "https://johndoherty.github.io"
twitter_username: john_c_doherty
github_username:  johndoherty
show_excerpts: True

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
